### ISSUE TITLE
付款后用户信息没有更新

### ISSUE THREAD

**Issue by yesmore** [weijunext/smart-excel-ai#1]
感谢作者的项目！

我在实际部署中遇到了一个问题，相关操作：

- 在LemonSqueeze创建了一个Product，并按照文档添加了两个VARIANT，订阅和加油包
- 关闭 Test mode
- 用户可以正常登录（我使用的Github登录，数据库、redis连接正常）
- 付款（使用支付宝付款，订阅以及加油包方式都尝试过一次）后，跳转回Billing页面

期待结果：Billing信息展示为Pro plan（非free plan）
实际结果：Billing信息依旧是free plan

查询vercel log，发现webhook有404错误：
`[POST] /api/payment/webhooks?nxtPslug=api%2Fpayment%2Fwebhooks status=404`

我的webhook配置：`https://lemonpay.oihub.cc/api/payment/webhooks`

![779c070262fc9f156f0d6dd3bb63e7af](https://github.com/weijunext/smart-excel-ai/assets/89140804/89a78098-a686-493a-aa9b-945fc6f7a97f)

查看ls的Settings -> Webhooks，发现也有几个404：
![f41039260ca21c5b228c44cc24cfab2f](https://github.com/weijunext/smart-excel-ai/assets/89140804/273736b0-66db-4fdf-bbd1-0cc3d501d131)

请问是我的配置有什么问题吗？（代码没有改动）

**Comment by weijunext** [comment]
代码没有改动的话api是 `/api/payment/webhook`，没有`s`，请先确认是否这个问题

**Comment by yesmore** [comment]
我多加了s，蠢哭（生无可恋脸
