### ISSUE TITLE
应该开放AI host可配置，支持下第三方代理地址，只要兼容openai就好了

### ISSUE THREAD

**Issue by hafung** [weijunext/smart-excel-ai#12]
如题

**Comment by Mmmm008** [comment]
已收到。

**Comment by hafung** [comment]
看package里有强依赖了openai的库，感觉都可以不用...  方便后续如果能支持其他LLM 或者 国内的（合规问题）  甚至本地LLM接口（工作量应该还好，因为基本都兼容openai的 233）

**Comment by hafung** [comment]
openai官方的库 已经支持 配置 代理地址了   OPENAI_BASE_URL
