### ISSUE TITLE
psgl的表要先建么 还是说部署到vercel的时候 自动会检测、执行？

### ISSUE THREAD

**Issue by hafung** [weijunext/smart-excel-ai#13]
readme里没看到相关说明（对nextjs不熟

**Comment by weijunext** [comment]
要手动建，然后配置环境变量。简单的可以用vercel平台的postgresql，可以免费建一个

**Comment by hafung** [comment]
不对啊  我看 build命令 有包含了啊 "build": "contentlayer build && prisma generate && prisma db push && next build",   这样vercel在自动构建的时候 不会自动检查、创建表(schema)么？

**Comment by weijunext** [comment]
> 不对啊 我看 build命令 有包含了啊 "build": "contentlayer build && prisma generate && prisma db push && next build", 这样vercel在自动构建的时候 不会自动检查、创建表(schema)么？

prisma不是postgresql，你有表了、配置了环境变量，prisma的push才知道push到哪里
