### ISSUE TITLE
关于env  prompt

### ISSUE THREAD

**Issue by hafung** [weijunext/smart-excel-ai#14]
# PROMPT
PREFIX_PROMPT=
SUFFIX_PROMPT=
USING_CONTENT_FORMATTING=
LANGUAGE_TIP=
THANK_YOU=

这几个提示词相关的环境变量有什么作用么？ 可以不配么

**Comment by weijunext** [comment]
拼接成完整prompt用的。你可以根据自己的prompt去设计，不需要的环境变量删掉，代码里引用的环境变量参数也删掉，就可以了

**Comment by hafung** [comment]
可以开源下相关prompt么。、。
