### ISSUE TITLE
vercel 中部署就报错 code: 'ERR_INVALID_ARG_TYPE'

### ISSUE THREAD

**Issue by allanxia** [weijunext/smart-excel-ai#16]
![vercel](https://github.com/weijunext/smart-excel-ai/assets/12131922/db03b866-e3fa-4f2f-8177-55192af954b0)

在vercel中开始部署就报错，已经创建了.env文件，但是还没有填写内容，错误看起来有2个：
1. 第一个错误完全没看明白是什么回事？
2. 第二个错误看起来是PostgreSQL没安装，这个是需要安装PostgreSQL（比如在vercel中申请一个），然后把地址配置到.env中么？

Done in 34.9s
--
00:29:34.695 | Detected Next.js version: 13.5.6
00:29:34.751 | Running "pnpm run build"
00:29:35.217 |  
00:29:35.217 | > @ build /vercel/path0
00:29:35.218 | > contentlayer build && prisma generate && prisma db push && next build
00:29:35.218 |  
00:29:37.303 | Generated 1 documents in .contentlayer
00:29:37.312 | TypeError: The "code" argument must be of type number. Received an instance of Object
00:29:37.312 | at process.set [as exitCode] (node:internal/bootstrap/node:123:9)
00:29:37.313 | at Cli.runExit (/vercel/path0/node_modules/.pnpm/registry.npmmirror.com+clipanion@3.2.1_typanion@3.14.0/node_modules/clipanion/lib/advanced/Cli.js:232:26)
00:29:37.313 | at run (file:///vercel/path0/node_modules/.pnpm/registry.npmmirror.com+@contentlayer+cli@0.3.4_esbuild@0.19.5/node_modules/@contentlayer/cli/src/index.ts:39:3)
00:29:37.313 | at main (/vercel/path0/node_modules/.pnpm/registry.npmmirror.com+contentlayer@0.3.4_esbuild@0.19.5/node_modules/contentlayer/bin/cli.cjs:5:3) {
00:29:37.313 | code: 'ERR_INVALID_ARG_TYPE'
00:29:37.313 | }
00:29:37.867 | Environment variables loaded from .env
00:29:37.870 | Prisma schema loaded from prisma/schema.prisma
00:29:38.297 |  
00:29:38.298 | ✔ Generated Prisma Client (v5.5.2) to ./node_modules/.pnpm/registry.npmmirror.com+@prisma+client@5.5.2_prisma@5.5.2/node_modules/@prisma/client in 58ms
00:29:38.298 |  
00:29:38.298 | Start using Prisma Client in Node.js (See: https://pris.ly/d/client)

**Comment by allanxia** [comment]
问题已经解决了

**Comment by weijunext** [comment]
env配置补充一下。postgres要有，可以用vercel的

**Comment by zy111x** [comment]
> 问题已经解决了

怎么解决的呀，老哥，在vercel中部署的话必须要有哪些准备，.env中哪些参数必须要
