### ISSUE TITLE
odule not found: Package path ./generated is not exported from package F:\smart-excel-ai-main\node_modules\contentlayer (see exports field in F:\smart-excel-ai-main\node_modules\contentlayer\package.json)

### ISSUE THREAD

**Issue by zjrwtxdaydayup** [weijunext/smart-excel-ai#7]
![image](https://github.com/weijunext/smart-excel-ai/assets/139489333/f10b1642-5076-4da5-8d87-2f2fb9d96c75)

**Comment by zjrwtxdaydayup** [comment]
依赖都安装了的 看了contentlayer 上的github库也有不少人有同样的问题 请作者帮忙看看 谢谢

**Comment by zjrwtxdaydayup** [comment]
https://github.com/contentlayerdev/contentlayer/issues/415

**Comment by weijunext** [comment]
修改`package.json`里以下三个包的版本：

```
 "next": "13.2.4",
 "next-contentlayer": "0.3.1",
"contentlayer": "0.3.1"
```

删掉 `node_modules`、`. contentlayer`，重新 `npm install` 或者 `yarn`，看看问题是否还存在

**Comment by zjrwtxdaydayup** [comment]
作者你好，修改后，还是同样的问题
![image](https://github.com/weijunext/smart-excel-ai/assets/139489333/edea23a2-b421-45d0-8ebc-e009de3ee74a)

**Comment by weijunext** [comment]
能否在github发布一份你当前的代码，邮箱（weijunext@gmail.com）发给我也可，我调试看看

**Comment by zjrwtxdaydayup** [comment]
> 能否在github发布一份你当前的代码，邮箱（[weijunext@gmail.com](mailto:weijunext@gmail.com)）发给我也可，我调试看看

你好 已经发邮件给你的邮箱了 麻烦了
![image](https://github.com/weijunext/smart-excel-ai/assets/139489333/e94d058d-497d-4750-8e6a-0c55df7690f2)

**Comment by weijunext** [comment]
我测试了还是没问题。你用 `pnpm i`安装依赖，然后启动，试试看

**Comment by zjrwtxdaydayup** [comment]
> 我测试了还是没问题。你用 `pnpm i`安装依赖，然后启动，试试看

我在win上测试还是不行，在gitpod的linux环境里就没问题，会不会是那个包没兼容win：
![image](https://github.com/weijunext/smart-excel-ai/assets/139489333/29c1f168-b449-46c8-80c9-a4f3d1801a99)
